name: sd_replay_parser
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  http: ^1.2.2
  build_runner: ^2.4.14
  json_serializable: ^6.9.2

