name: pokemon_core
description: The core library for this pokemon project
version: 1.0.0

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  json_serializable: ^6.9.2
  build_runner: ^2.4.14

